import Head from "next/head"
import Navbar from "../../components/navbar/Navbar"
import Footer from "../../components/footer/Footer"
import Features from "../../components/features/Features"

export default function FeaturePage() {
    return (
        <div>
            <Head>
                <title>The Features | Folium</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Navbar active="features"/>
                <Features />
                <Footer />
            </main>
        </div>
    )
}